### ISSUE TITLE
Can't see Amoled Patched or Stock Patched

### ISSUE THREAD

**Issue by GandalfNotUse** [xManager-App/xManager#290] opened 2023-03-09 15:31 UTC
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  Samsung A33
- Android Version:  13
- ROM Version:  One UI 5.1
- xManager Version:  4.6
```

### 📝 Description

1.mine xManager is not showed a stock or amoled list of version
2.
3.
...

### 📸 Screenshots

![Screenshot_20230309_223048_xManager](https://user-images.githubusercontent.com/83999306/224072802-cdc8a25d-d608-4166-aff6-e7067530a011.jpg)

**Comment by DarkCrypt** [comment] 2023-03-09 18:33
Duplicate of #276 & #268.

I had the same issue. Hit "REFETCH AND REBOOT" on the left at the bottom of page in Settings. This should fix it.

You can also read the 2 threads mentioned.

**Comment by GandalfNotUse** [comment] 2023-03-09 22:58
> Duplicate of #276 & #268.
> 
> I had the same issue. Hit "REFETCH AND REBOOT" on the left at the bottom of page in Settings. This should fix it.
> 
> You can also read the 2 threads mentioned.

![Screenshot_20230310_055744_xManager.jpg](https://user-images.githubusercontent.com/83999306/224179212-f480ce75-234e-4924-8e44-05e6cf161269.jpg)

That's fix it thank you for guide

**Closed** 2023-03-10 18:38 UTC
